---
downloads: ~/.ansible-downloads/

general:
  local_home: "{{ lookup('env','HOME')}}"
  user_name: "{{ lookup('env','USER')}}"


configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - News
  - Music
  - Safari
  - Mail
  - Maps
  - Contacts
dockitems_persist:
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 1
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 2
 - name: "KeePassXC"
   path: "/Applications/KeePassXC.app/"
   pos: 3
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 4

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

configure_dotfiles: true
dotfiles_repo: https://github.com/davidcolinsmith/dotfiles.git
dotfiles_repo_branch: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - zshrc
  - gitignore
  - inputrc
  - osx
  - vimrc
  - p10k.zsh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - automake
  - aws-iam-authenticator
  - aws-okta
  - awscli
  - docker-machine
  - dockerfile-lint
  - eksctl
  - flake8
  - fluxctl
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - helm
  - httpie
  - iperf
<<<<<<< HEAD
  - jsonlint
  - markdownlint-cli
  - jq
  - mtr
=======
  - libevent
  - sqlite
>>>>>>> upstream/master
  - nmap
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - the_silver_searcher
    # - terraform
  - terraform-docs
    #  - terragrunt
  - tfenv
  - tflint
  - tgenv
  - tmux
  - tree
  - vim
  - watch
  - wget
  - yq
  - zsh
  - zsh-history-substring-search

<<<<<<< HEAD
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
=======
homebrew_taps: []
>>>>>>> upstream/master

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bitwig-studio
  - chromedriver
  - dropbox
  - google-chrome
  - iterm2
  - keepassxc
  - keybase
  - remarkable
  - slack
  - spotify
  - spotify-now-playing
  - steam
  - zenmap
  - font-hack-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
